# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 674)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.table_magaz = QtWidgets.QTableWidget(self.tab)
        self.table_magaz.setObjectName("table_magaz")
        self.table_magaz.setColumnCount(0)
        self.table_magaz.setRowCount(0)
        self.verticalLayout_2.addWidget(self.table_magaz)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.table_product = QtWidgets.QTableWidget(self.tab_2)
        self.table_product.setObjectName("table_product")
        self.table_product.setColumnCount(0)
        self.table_product.setRowCount(0)
        self.verticalLayout_3.addWidget(self.table_product)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.table_dvig = QtWidgets.QTableWidget(self.tab_3)
        self.table_dvig.setObjectName("table_dvig")
        self.table_dvig.setColumnCount(0)
        self.table_dvig.setRowCount(0)
        self.verticalLayout_4.addWidget(self.table_dvig)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 27))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.open_magaz = QtWidgets.QAction(MainWindow)
        self.open_magaz.setObjectName("open_magaz")
        self.zagrysit = QtWidgets.QAction(MainWindow)
        self.zagrysit.setObjectName("zagrysit")
        self.sohranit = QtWidgets.QAction(MainWindow)
        self.sohranit.setObjectName("sohranit")
        self.open_product = QtWidgets.QAction(MainWindow)
        self.open_product.setObjectName("open_product")
        self.open_dvig = QtWidgets.QAction(MainWindow)
        self.open_dvig.setObjectName("open_dvig")
        self.save_magaz = QtWidgets.QAction(MainWindow)
        self.save_magaz.setObjectName("save_magaz")
        self.menu.addAction(self.open_magaz)
        self.menu.addAction(self.save_magaz)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Магазины"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Товары"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Движение товаров"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.open_magaz.setText(_translate("MainWindow", "Открыть таблицу"))
        self.zagrysit.setText(_translate("MainWindow", "Загрузить"))
        self.sohranit.setText(_translate("MainWindow", "Сохранить"))
        self.open_product.setText(_translate("MainWindow", "Открыть товары"))
        self.open_dvig.setText(_translate("MainWindow", "Открыть движение товаров"))
        self.save_magaz.setText(_translate("MainWindow", "Сохранить"))
